#!/bin/bash

if [ -z $@ ]
   then
	for arg in {01..18}
	do
	    ping -c 1 -q rpi$arg 2>&1 >/dev/null
	    if [ $? -eq 0 ]
	       then
		echo "rpi$arg : alive"
		else echo "rpi$arg : dead"
		fi
	done
else for arg in $@
do
     ping -c 1 -q $arg 2>&1 >/dev/null
     if [ $? -eq 0 ]
     	then
		echo "$arg : alive"
	else echo "$arg : dead"
	fi
done
fi
